The Importing the module Numpy 

In [1]:
import numpy as np

assigning the Senses of Census data set to the data_file.
From this step onwards to access the dataset we should use data_file.

In [2]:
data_file = '/content/makeSenseOfCensus.csv'

Converting the dataSet in to array to perform the operations.
providing the name Data to the array.


In [3]:
data = np.genfromtxt(data_file, delimiter=',',skip_header = 1)
data

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [38.,  9.,  4., ...,  0., 40.,  0.],
       ...,
       [48., 13.,  4., ...,  0., 58.,  1.],
       [40., 10.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 50.,  1.]])

adding the new row values to the array which is new_record.

after adding the new record the data is assigned to df



In [4]:
new_record=[[50, 9, 4, 1, 0, 0, 40, 0]]
new_record
df = np.concatenate((data, new_record))
print(df)

[[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]
 [50.  9.  4. ...  0. 40.  0.]]


- Create a new array called 'age' by taking only age column(age is the column with index 0) of 'census' array.
- printing tthe shape of the age data.
- printing the size of the age data.


In [10]:
from numpy.core.fromnumeric import shape
age = df[:,0]
print(age)
print(age.shape)
print(age.size)

[39. 50. 38. ... 40. 39. 50.]
(1001,)
1001


# Check if it's a young country or old country
# Method - 1 

- Finding the max age and store it in a variable called 'max_age'.

- Printing the maximum age in the age data.

In [11]:
max_age = age.max()
print(max_age)

90.0


- Finding the min age and store it in a variable called 'min_age'.

- Printing the minimum age in the age data.

In [13]:
min_age=age.min()
print(min_age)

17.0


- Finding the mean of the age  age and store it in a variable called 'mean_age'.

- Printing the mean value in the age data.

In [15]:
mean_age=age.mean()
print(mean_age)

38.06293706293706


- Finding the standard deviaton of the age and store it in a variable called 'sd_age'.

- Printing the standard deviation of the age in the age data.

In [16]:
sd_age = np.std(age)
print(sd_age)

13.341478176165857


Fom the mean of the data we can say that the country is young.


# Method-2 for checking the country is young.
- using array indexing.


Cheking the data for the age between the 1 to 19 and assigning the data to Children by using the method called array indexing.


In [26]:
children=age[[age > 1] and [age<19]]
print(children)
print("Number of childerns in the country:" ,children.size)

[18. 18. 18. 17. 18. 18. 18. 17. 18. 17. 17. 17. 17. 17. 17. 17. 17. 17.
 18. 18. 17. 17. 17. 17. 18. 18. 17. 18. 18. 17. 17. 17. 18. 17. 18. 18.]
Number of childerns in the country: 36


<ipython-input-26-f771d2857737>:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  children=age[[age > 1] and [age<19]]


Cheking the data for the age between the 20 to 59 and assigning the data to young by using the method called array indexing

In [30]:
young=age[[age > 20] and [age < 59]]
#print(young)
print("Number of young in the country:" , young.size)

Number of young in the country: 918


<ipython-input-30-00a0b270756c>:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  young=age[[age > 20] and [age < 59]]


Cheking the data for the age Greater than 60  and assigning the data to senior_citizen by using the method called array indexing

In [31]:
senior_citizen = age[age > 60]
print(senior_citizen)
print("Number of senior_citizen in the country:" , senior_citizen.size)

[79. 67. 76. 61. 70. 64. 71. 68. 66. 64. 90. 66. 75. 65. 64. 61. 65. 77.
 62. 76. 63. 66. 67. 65. 62. 63. 80. 67. 63. 72. 62. 74. 67. 72. 69. 65.
 65. 71. 70. 66. 65. 61. 61. 68. 64. 64. 62. 73. 72. 63. 62. 61. 71. 63.
 63. 67. 81. 64. 67. 78. 63.]
Number of senior_citizen in the country: 61


From the data we can say that the young value is greater than the senior_citizen. so that finally we can say that the country is young Country.

# Method-3 for checking country is young.
- using looping technique.

In [42]:
child=0
young=0
seniorcitizen=0
for i in range(len(age)):
  if((age[i]>1 and age[i]<19)):
    child+=1
  elif((age[i]>19 and age[i]<59)):
    young+=1
  elif(age[i]>60):
    seniorcitizen+=1
print(child)
print(young)
print(seniorcitizen)

36
861
61


from the count of the young and child we can clearly say that the country is young country.


# Let's check the country's race distribution to identify the minorities


In order to check the race distributin of the race we need to work on the index 2

In [6]:
race = df[:,2]
print(race)

[4. 4. 4. ... 4. 4. 4.]


identifying the different race form  the data

In [7]:
race_0 = race[race == 0]
race_1 = race[race == 1]
race_2 = race[race == 2]
race_3 = race[race == 3]
race_4 = race[race == 4]

Finding the length of the each race value. so that we can identify the majority and minarity in the data

In [8]:
len_0 = len(race_0)
print(len_0)
len_1 = len(race_1)
print(len_1)
len_2 = len(race_2)
print(len_2)
len_3 = len(race_3)
print(len_3)
len_4 = len(race_4)
print(len_4)

10
27
110
6
848


# As per govt. records citizens above 60 should not work more than 25 hours a week. Let us check if the policy is in place

defining the age with greater that 60 and assigning the value as senior_citizeen

In [10]:
age=df[:,0]
print(age)
print(len(age))
senior_citizen = age[age > 60]
print(senior_citizen)
print(len(senior_citizen))

[39. 50. 38. ... 40. 39. 50.]
1001
[79. 67. 76. 61. 70. 64. 71. 68. 66. 64. 90. 66. 75. 65. 64. 61. 65. 77.
 62. 76. 63. 66. 67. 65. 62. 63. 80. 67. 63. 72. 62. 74. 67. 72. 69. 65.
 65. 71. 70. 66. 65. 61. 61. 68. 64. 64. 62. 73. 72. 63. 62. 61. 71. 63.
 63. 67. 81. 64. 67. 78. 63.]
61


getting the data of workinghours for the cences data which is with index value 6

In [11]:
workinghours=df[:,6]
print(workinghours)
print(len(workinghours))


[40. 13. 40. ... 40. 50. 40.]
1001


Checking number of people are satisfing the governament policy.

In [12]:
policy=0
working_hours=[]
age_ex=[]
print(type(working_hours))
for i in range(len(age)):
  if (age[i]>60 and workinghours[i]>25):
    policy+=1
    working_hours.append(workinghours[i])
    age_ex.append(age[i])
print("policy is vilated by :",policy,"menbers")
print(working_hours)
print(age_ex)
print(len(age_ex))

<class 'list'>
policy is vilated by : 37 menbers
[40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 50.0, 40.0, 40.0, 40.0, 40.0, 45.0, 55.0, 40.0, 40.0, 40.0, 35.0, 40.0, 48.0, 40.0, 40.0, 30.0, 59.0, 50.0, 40.0, 40.0, 45.0, 40.0, 40.0, 48.0, 40.0, 40.0, 55.0, 40.0, 30.0, 40.0, 40.0]
[76.0, 61.0, 70.0, 64.0, 64.0, 90.0, 66.0, 65.0, 64.0, 61.0, 77.0, 63.0, 66.0, 65.0, 62.0, 63.0, 63.0, 62.0, 67.0, 72.0, 69.0, 65.0, 65.0, 61.0, 61.0, 64.0, 64.0, 62.0, 73.0, 62.0, 61.0, 71.0, 63.0, 67.0, 81.0, 67.0, 78.0]
37


# Method 2 : As per govt. records citizens above 60 should not work more than 25 hours a week. Let us check if the policy is in place

In [26]:
senior_citizen = age[age > 60]
print(senior_citizen)
working_hours = df[:,6]
print(working_hours)
senior_citizen_len = len(senior_citizen)
print(senior_citizen_len)
avg_working_hours = working_hours_sum / senior_citizen_len
print(avg_working_hours)

[79. 67. 76. 61. 70. 64. 71. 68. 66. 64. 90. 66. 75. 65. 64. 61. 65. 77.
 62. 76. 63. 66. 67. 65. 62. 63. 80. 67. 63. 72. 62. 74. 67. 72. 69. 65.
 65. 71. 70. 66. 65. 61. 61. 68. 64. 64. 62. 73. 72. 63. 62. 61. 71. 63.
 63. 67. 81. 64. 67. 78. 63.]
[40. 13. 40. ... 40. 50. 40.]
61
25.40983606557377
